language: node_js
node_js:
  - "7.2.1"
script:
  - echo "Deploying VueJS To-do List ..."
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn global add firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
